theme: odh-fbe
baseURL: "https://example.com"
languageCode: en
title: Open Data Hub - Develop digital solutions based on real data
markup:
  goldmark:
    renderer:
      unsafe: true

params:
  logo: img/NOI_OPENDATAHUB_NEW_BK_nospace-01.svg
  logo_NOI: img/NOI_1_BK.svg
  web_NOI: "https://noi.bz.it"
  favicon: img/logo-open-data-hub.png
  author: Open Data Hub
  description: >-
    Open Data Hub is your access point to relevant data. You and your service
    providers can use Open Data Hub for all channels of digital communication.
    The data is updated on a regular basis and easily accessible.
  PrivacyUrl: "https://noi.bz.it/en/privacy-cookie-policy"
  plugins:
    css:
      - URL: /css/animate.css
      - URL: /css/bootstrap.css
      - URL: /css/style.css
      - URL: /css/table-comparison.css
      - URL: /css/custom.css
      - URL: /css/responsive.css
      - URL: /css/availability.css
      - URL: /css/contact-form.css
      - URL: >-
          https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css
      - URL: https://scripts.opendatahub.testingmachine.eu/cookieconsent/opendatahub/cookieconsent.css

    js:
      - URL: /js/jquery.min.js
      - URL: /js/jquery.easing.1.3.js
      - URL: /js/bootstrap.min.js
      - URL: /js/jquery.waypoints.min.js
      - URL: /js/jquery.stellar.min.js
      - URL: /js/main.js
      - URL: /js/table-comparison.js
      - URL: https://scripts.opendatahub.testingmachine.eu/cookieconsent/cookieconsent.js
      - URL: https://scripts.opendatahub.testingmachine.eu/cookieconsent/cookieconsent-init.js

  footer:
    logo: /img/NOI_OPENDATAHUB_NEW_WH-02.png
    menu_title_1: <a href="/services">Services</a>
    menu_title_2: <a href="/quickstart">Quickstart</a>
    menu_title_3: <a href="/community">Community</a>
    menu_title_4: <a href="/datasets">Data</a>
    github: "https://github.com/noi-techpark/"
    facebook: "https://www.facebook.com/opendatahub/"
    telegram: "https://t.me/OpenDataHub"
    element: "https://matrix.to/#/#main-room-odh22:matrix.virtual.software.bz.it"
    copyright: >-
      NOI AG - Via Volta 13/A, I-39100 Bolzano - VAT No.: 02595720216 -
      Endowment capital 110.740.000 â‚¬ - <a href="https://noi.bz.it/en/privacy-cookie-policy" target="_blank">Privacy</a>

taxonomies:
  type: datatype

menu:
  main:
    - identifier: services
      URL: /services
      name: Services
      weight: 1

    - parent: services
      name: Data access
      URL: /data-access
      weight: 1

    - parent: services
      name: Data sharing
      URL: /data-sharing
      weight: 2

    - parent: services
      name: Data visualization
      URL: /data-visualization
      weight: 3

    # - parent: services
    #   name: Use Cases
    #   URL: /services/#sm-tag-data-visualization
    #   weight: 4

    - identifier: use-cases
      name: Use Cases
      URL: /use-cases
      weight: 2

    - parent: use-cases
      name: Kultivas
      URL: /kultivas
      weight: 1

    # - parent: use-cases
    #   name: UC Data Sharing
    #   URL: /use-cases/#sm-tag-data-visualization
    #   weight: 2

    # - parent: use-cases
    #   name: UC Data Visualization
    #   URL: /use-cases/#sm-tag-data-visualization
    #   weight: 3

 


    - identifier: datasets
      URL: /datasets
      name: Datasets
      weight: 3

   

    - identifier: quickstart
      URL: /quickstart
      name: Quickstart
      weight: 4

    - identifier: community
      URL: /community
      name: Community
      weight: 5

    - parent: community
      name: Data Providers
      URL: /community/#sm-tag-data-providers
      weight: 1

    - parent: community
      name: Data Consumers
      URL: /community/#sm-tag-data-consumers
      weight: 2

    # - parent: community
    #   name: Contributors
    #   URL: /community/#sm-tag-data-consumers
    #   weight: 3

    # - parent: community
    #   name: Get involved
    #   URL: /community/#sm-tag-data-consumers
    #   weight: 4

    - identifier: events
      URL: /events
      name: Events
      weight: 6

    - parent: events
      name: Upcoming events
      URL: /events/#sm-tag-upcoming-events
      weight: 1

    - parent: events
      name: Past events
      URL: /events/#sm-tag-past-events
      weight: 2

  footer1:
    - URL: /data-sharing/
      name: Data Sharing

    - URL: /data-access/
      name: Data Access

    - URL: /data-visualization
      name: Data Visualization

  footer2:
    # - URL: 'https://docs.opendatahub.com'
    #   name: Documentation
    #   weight: 1

    - URL: "https://databrowser.opendatahub.com/"
      name: Data browser
      weight: 2

    - URL: "https://analytics.opendatahub.com/"
      name: Analytics tool
      weight: 3

    - URL: "https://webcomponents.opendatahub.com/"
      name: Web Components
      weight: 4

  footer3:
    - URL: /community
      name: Community

    - URL: /events
      name: Events

  footer4:
    - URL: /datasets
      name: Datasets
      weight: 2

    - URL: "https://opendatahub.readthedocs.io/en/latest/datasets.html"
      name: Documentation
      weight: 3
