name: CI opendatahub-website

on: 
  push:
    branches: [development, master]
    paths:
      - "!README.md"

  pull_request:
    branches: [development, master]
    paths:
      - "!README.md"


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: clone into repo
        uses: actions/checkout@v2

      - name: install hugo
        run: sudo apt-get install hugo

      - name: setup hugo
        run: hugo -s src -d ../target

    

